name: critter_care
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.1.0
  provider: ^6.0.5
  get_it: ^7.6.7
  image_picker: ^1.2.0
  dio: ^5.7.0
  http_parser: ^4.0.2
  mime: ^1.0.5
  equatable: ^2.0.7
  flutter_svg: ^2.1.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.3.0
  shared_preferences: ^2.3.2

dependency_overrides:
  http: 1.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/features/homepage/
    - assets/features/onboarding/
    - assets/features/planner/
    - assets/features/squads/icons/
    - assets/avatar/
    - assets/global/icons/
    
    # Avatar base parts
    - assets/avatar/base/Creature.svg
    - assets/avatar/base/Base_Hat.svg

    # Avatar accessories
    - assets/avatar/accessories/Balloon.svg
    - assets/avatar/accessories/Flower.svg
    - assets/avatar/accessories/Glasses.svg
    - assets/avatar/accessories/Watch.svg
    - assets/avatar/accessories/Wings.svg

    # Avatar hats / hair
    - assets/avatar/hat/Bunny.svg
    - assets/avatar/hat/Crown.svg
    - assets/avatar/hat/Hat.svg
    - assets/avatar/hat/Jambul.svg
    - assets/avatar/hat/Pajamas Hat.svg
    - assets/avatar/hat/Ponytail.svg

    # Avatar shirts
    - assets/avatar/shirt/Casual.svg
    - assets/avatar/shirt/Dress.svg
    - assets/avatar/shirt/Pajamas.svg
    - assets/avatar/shirt/Suit.svg

    # Squad icons
    - assets/features/squads/icons/ic_book.svg
    - assets/features/squads/icons/ic_star.svg
    
    # Auth icons
    - assets/features/auth/blob/

    # Global icons
    - assets/global/icons/
