// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8NWN103anOADDy3-K8DmAb4HYbwCcCgk',
    appId: '1:175309600186:web:96a5b7c86e6fad7bb95983',
    messagingSenderId: '175309600186',
    projectId: 'crittercoach-78a9c',
    authDomain: 'crittercoach-78a9c.firebaseapp.com',
    storageBucket: 'crittercoach-78a9c.firebasestorage.app',
    measurementId: 'G-VR6VV8GW4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3K4BZVXy8tZDwgOOi7WT-PPvDVUXzuhI',
    appId: '1:175309600186:android:12a7ea8e6f25f9c9b95983',
    messagingSenderId: '175309600186',
    projectId: 'crittercoach-78a9c',
    storageBucket: 'crittercoach-78a9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWXsanJ-jkSJRRnNmTzUbzHo0A7BMsYV0',
    appId: '1:175309600186:ios:096761f9cc9283eeb95983',
    messagingSenderId: '175309600186',
    projectId: 'crittercoach-78a9c',
    storageBucket: 'crittercoach-78a9c.firebasestorage.app',
    iosBundleId: 'com.mycompany.crittercare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8NWN103anOADDy3-K8DmAb4HYbwCcCgk',
    appId: '1:175309600186:web:dd2a55ec939b695fb95983',
    messagingSenderId: '175309600186',
    projectId: 'crittercoach-78a9c',
    authDomain: 'crittercoach-78a9c.firebaseapp.com',
    storageBucket: 'crittercoach-78a9c.firebasestorage.app',
    measurementId: 'G-1H4NEKJ3K9',
  );
}
